server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 500

spring:
  profiles:
    active: local
jwt:
  secret: qwerasdfzxcvdsafdsaffdasafdfdsafdsafdsafdsasfda
  access-token-expiration: 86400000
  refresh-token-expiration: 2592000000
